name: Analyze

on:
  push:
    branches:
      - '*'

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Linter
        run: flutter analyze --fatal-infos
